
services:
  # База данных
  db:
    image: postgres:15
    container_name: online-courses-db
    environment:
      POSTGRES_DB: courses
      POSTGRES_USER: courses
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U courses -d courses"]
      interval: 5s
      timeout: 5s
      retries: 10


  # Бэкенд (Go)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    container_name: online-courses-backend
    environment:
      DB_URL: "postgres://courses:securepass@db:5432/courses?sslmode=disable"
      DB_HOST: db 
      JWT_SECRET: "online-courses-super-secret-jwt-key-2026"
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      SMTP_HOST: ${SMTP_HOST}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_USER: ${SMTP_USER}
      SMTP_PASS: ${SMTP_PASS}
      SMTP_FROM: ${EMAIL_FROM}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend/migrations:/app/migrations
      - ./backend/seed:/app/seed
    command: >
      sh -c "
        echo 'Waiting for DB...' &&
        until pg_isready -h db -U courses -d courses; do sleep 2; done &&
        echo 'Running migrations...' &&
        /usr/local/bin/migrate -path /app/migrations -database $$DB_URL up &&
        if [ \"$${RUN_SEED:-true}\" = \"true\" ]; then
          echo 'Running seed data...' &&
          /usr/local/bin/migrate -path /app/seed -database \"$$DB_URL&x-migrations-table=schema_seed_migrations\" up;
        fi &&
        echo 'Starting Go server on :8080...' &&
        ./server
      "


  # Фронтенд (React SPA)
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    container_name: online-courses-frontend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - backend
  caddy:   
    image: caddy:2
    container_name: online-courses-caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./backend/Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy-data:/data
      - caddy-config:/config
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
    depends_on:
      - frontend
      - backend

volumes:
  pgdata:
  caddy-data:
  caddy-config:    

