# Dockerfile.backend
FROM golang:1.25-alpine AS builder

WORKDIR /app

RUN apk add --no-cache git

# Копируем зависимости
COPY go.mod go.sum ./
RUN go mod download

# Копируем исходники
COPY . .

# Собираем бинарник
RUN CGO_ENABLED=0 GOOS=linux go build -o server ./cmd/server

RUN go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@v4.16.0

# Финальный образ
FROM alpine:latest
RUN apk --no-cache add ca-certificates postgresql-client

WORKDIR /app

COPY --from=builder /app/server .
COPY --from=builder /app/migrations ./migrations/
COPY --from=builder /app/seed ./seed/
COPY --from=builder /go/bin/migrate /usr/local/bin/

EXPOSE 8080
CMD ["./server"]