server {
    listen 80;
    
    # Корень, где лежит собранный фронтенд (dist)
    root /usr/share/nginx/html;

    location / {
        index index.html index.htm;
        # Если файл не найден (например, роут React), отдаем index.html
        try_files $uri $uri/ /index.html;
    }

    # Явно укажем обработку картинок, чтобы Nginx не путал их с HTML
    location /images/ {
        alias /usr/share/nginx/html/images/;
        expires 7d;
        add_header Cache-Control "public, no-transform";
    }
}